package com.davidpopayan.sena.evs.controllers.models;

public class Constants {
    public static final String DATABASE_NAME = "datos.db";
    public static final int DATABASE_VERSION = 1;
    public static final String TABLE_DATOS = "CREATE TABLE DATOS (NUMERO INTEGER PRIMARY KEY AUTOINCREMENT, FECTAMITAJE TEXT, PRIMERN TEXT, SEGUNDON TEXT, PRIMERA TEXT SEGUNDOA TEXT, TIPOID TEXT ,NUMEROID TEXT, EPS TEXT, IPS TEXT, TELEFONO TEXT, DIRECCION TEXT, FECNAC TEXT, EDAD INTEGER, EDADCATEGORIZADA TEXT, GENERO TEXT, TALLA INTEGER, PESO INTEGER, PERIMETROA INTEGER, REALIZAAF TEXT, FRECUENCIAVF TEXT, MEDICAMENTOSI TEXT, GLUCOSAALTA TEXT, IMC INTEGER, CLASIFICACIONIMC TEXT, RIESGODIABETES TEXT, PRESIONAS INTEGER, PRESION DIASTIOLICA INTEGER, PRESIONARTERIAL TEXT, DIABETES TEXT, FUMA TEXT, PORCENTAJERIESGO TEXT, PACIENTEPRESENTARIESGO TEXT, DETALLEDP TEXT);";
}
