package com.davidpopayan.sena.evs.controllers.models;

public class Constants {
    public static final String DATABASE_NAME = "datos.db";
    public static final int DATABASE_VERSION = 1;
    public static final String TABLE_DATOS = "CREATE TABLE DATOS (NUMERO INTEGER PRIMARY KEY AUTOINCREMENT, FECTAMITAJE TEXT, NOMBREC TEXT ,TIPOID TEXT ,NUMEROID TEXT, EPS TEXT, IPS TEXT, TELEFONO TEXT, DIRECCION TEXT, FECNAC TEXT, EDAD INTEGER, EDADCATEGORIZADA TEXT, GENERO TEXT, TALLA INTEGER, PESO INTEGER, PERIMETROA INTEGER, REALIZAAF TEXT, FRECUENCIAVF TEXT, MEDICAMENTOSH TEXT, GLUCOSAALTA TEXT, DIABETESFAM TEXT,IMC INTEGER, CLASIFICACIONIMC TEXT, RIESGODIABETES TEXT, PRESIONAS INTEGER, PRESIONDIASTIOLICA INTEGER, PRESIONARTERIAL TEXT, DIABETES TEXT, FUMA TEXT, PORCENTAJERIESGO TEXT, RIESGOCARDIO TEXT,PACIENTEPRESENTARIESGO TEXT, DETALLEDP TEXT);";
}
